// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RouteServiceAPP.Infrastructure;

namespace SqliteMigrations.Migrations
{
    [DbContext(typeof(RouteServiceContext))]
    partial class RouteServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.BookedRoute", b =>
                {
                    b.Property<int>("BookedRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromName")
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToName")
                        .HasColumnType("TEXT");

                    b.HasKey("BookedRouteId");

                    b.HasIndex("FromName");

                    b.HasIndex("RouteId");

                    b.HasIndex("ToName");

                    b.ToTable("BookedRoutes");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.Locality", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Localities");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatEndNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatStartNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.RouteLocality", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalityName")
                        .HasColumnType("TEXT");

                    b.HasKey("RouteId", "OrdinalNumber");

                    b.HasIndex("LocalityName");

                    b.ToTable("RouteLocalities");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.Seat", b =>
                {
                    b.Property<int>("BookedRouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookedRouteId", "Number");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.BookedRoute", b =>
                {
                    b.HasOne("RouteServiceAPP.Domain.Entities.Locality", "From")
                        .WithMany()
                        .HasForeignKey("FromName");

                    b.HasOne("RouteServiceAPP.Domain.Entities.Route", "Route")
                        .WithMany("BookedRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RouteServiceAPP.Domain.Entities.Locality", "To")
                        .WithMany()
                        .HasForeignKey("ToName");

                    b.Navigation("From");

                    b.Navigation("Route");

                    b.Navigation("To");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.RouteLocality", b =>
                {
                    b.HasOne("RouteServiceAPP.Domain.Entities.Locality", "Locality")
                        .WithMany()
                        .HasForeignKey("LocalityName");

                    b.HasOne("RouteServiceAPP.Domain.Entities.Route", "Route")
                        .WithMany("RouteLocalities")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locality");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.Seat", b =>
                {
                    b.HasOne("RouteServiceAPP.Domain.Entities.BookedRoute", "BookedRoute")
                        .WithMany("Seats")
                        .HasForeignKey("BookedRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookedRoute");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.BookedRoute", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("RouteServiceAPP.Domain.Entities.Route", b =>
                {
                    b.Navigation("BookedRoutes");

                    b.Navigation("RouteLocalities");
                });
#pragma warning restore 612, 618
        }
    }
}
