version: "3.9"

services:
  route-service:
    container_name: route-service
    build: .
    ports:
      - "5010:5005"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5005"
    networks:
      - booking-app-net
    volumes:
      - "./dockerData/sqlite/:/var/sqlite/"
networks:
  booking-app-net:
    external: true
# For this to work, you must manually create network: docker network create booking-app-net